[workspace]
members = ["utralib"]

[package]
name = "atsama5d27"
version = "0.1.0"
edition = "2021"

[dependencies]
armv7 = { git = "https://github.com/Foundation-Devices/armv7.git", branch = "update" }
bitflags = "2.4.1"
rtt-target = { git = "https://github.com/Foundation-Devices/rtt-target.git", branch = "cortex-a", features = ["cortex-a"], optional = true }
utralib = { path = "./utralib", default_features=false, features = ["atsama5d27"] }
r0 = "1.0.0"
embedded-graphics = { version = "0.7.1", optional = true }
embedded-hal = { version = "0.2.7", features = ["unproven"], optional = true }

[features]
hal = ["embedded-hal"]
rtt = ["rtt-target"]
lcd-console = ["embedded-graphics"]

default = ["lcd-console"]

[profile.dev]
#codegen-units = 1
#debug = 2
#debug-assertions = true # <-
#incremental = false
#opt-level = 3 # <-
#overflow-checks = true # <-

[profile.release]
debug = 1
