# SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "One"
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
use_try_shorthand = true
wrap_comments = true
comment_width = 90
remove_nested_parens = true
unstable_features = true
use_field_init_shorthand = true

# NOTE:
# - Try to not add any more crates to the exclude list. Reduce it.
# - Needs nightly rustfmt.
ignore = []
